echo Adding group $GROUP_ID just in case ...
addgroup --system --gid $GROUP_ID docker || echo Group $GROUP_ID already exists which is OK.

echo Creating user $USER_ID ...
adduser --system --uid $USER_ID --disabled-password --gecos "" --ingroup $(getent group $GROUP_ID | cut -d: -f1) $(id -nu $USER_ID) || echo User $USER_ID already exists which is OK.
echo Adding user $USER_ID into group $GROUP_ID ...
usermod -a -G $(getent group $GROUP_ID | cut -d: -f1) $(id -nu $USER_ID)
echo Switching to user $USER_ID ...
su $(id -nu $USER_ID)